const { h1, h2, h3, p, b, i, bul, sbul, sp, pb, cb, tbl, center } = require('./content-data');

function getContent() {
  const c = [];
  c.push(h1('01. Introduction'));
  c.push(h2('1.1 Project Overview'));
  c.push(p('GreenHarvest is a comprehensive full-stack agriculture platform designed to bridge the gap between farmers, agricultural suppliers, and industry experts. The platform serves as a centralized hub where users can explore crop information, browse agricultural products, read informative blog posts, view image galleries, submit contact inquiries, and access a wealth of agricultural knowledge. Built entirely with modern web technologies, GreenHarvest delivers a rich, interactive user experience featuring smooth animations, dark/light theme support, fully responsive design, and a complete administrative backend for content management.'));
  c.push(p('The platform is structured as a monorepo containing two main applications: a RESTful API backend built with Node.js, Express, and MongoDB, and a dynamic single-page frontend built with React 18, Vite 5, and Tailwind CSS 3. The backend provides a comprehensive API with over 33 endpoints for managing crops, products, blog posts, user inquiries, testimonials, FAQs, services, user accounts, file uploads, and analytics. The frontend consumes these APIs to deliver an engaging and visually appealing user experience with 13 distinct page views and a 7-section admin panel.'));
  c.push(p('This technical documentation provides a comprehensive reference for developers, system administrators, and technical stakeholders who need to understand, maintain, or extend the GreenHarvest platform. It covers the complete architecture, all backend and frontend components, database schema, API endpoints, authentication flow, security measures, deployment procedures, and future development roadmap.'));
  c.push(h2('1.2 Project Name and Brand Identity'));
  c.push(p('The name GreenHarvest reflects the platform\'s core mission: promoting sustainable agriculture through the "Green" initiative while enabling prosperous yields with "Harvest." The visual identity uses a carefully curated color palette across five families that evoke nature and agriculture, creating a cohesive and immersive brand experience.'));
  c.push(p('The color system includes Earth tones representing soil and grounding, Leaf greens representing growth and vitality, Sprout greens representing young plants and potential, Sunset orange representing harvest and warmth, and Cream tones representing natural materials. The typography pairs Playfair Display serif font for headings with Inter sans-serif for body text, creating a modern yet organic feel. The UI design employs glass-morphism patterns with backdrop blur effects, subtle gradient accents, and nature-inspired decorative elements throughout.'));
  c.push(h2('1.3 Target Audience'));
  c.push(p('The platform serves multiple distinct user personas, each with specific needs and goals:'));
  c.push(p(b('Farmers and Agricultural Workers:'), ' The primary audience. They use the platform to research crop varieties, understand growing conditions including season, soil requirements, and water needs, discover agricultural products across multiple categories, read educational blog content, and connect with service providers in their region.'));
  c.push(p(b('Agricultural Suppliers and Vendors:'), ' Use the platform to list products such as seeds, fertilizers, equipment, pesticides, and organic supplies. The product catalog provides a marketplace for reaching potential buyers with detailed product descriptions, pricing, stock information, and imagery.'));
  c.push(p(b('Agronomists and Agricultural Experts:'), ' Contribute knowledge through the blog system, sharing best practices, research findings, cultivation techniques, and success stories with the broader farming community.'));
  c.push(p(b('General Users and Enthusiasts:'), ' Individuals interested in sustainable farming, home gardening, organic products, and agricultural education who explore the platform for information and inspiration.'));
  c.push(p(b('Platform Administrators:'), ' Manage all platform content through the comprehensive admin panel, including creating, editing, and deleting crops, products, blog posts, managing user accounts and roles, monitoring analytics, and responding to contact inquiries.'));
  c.push(h2('1.4 Key Features'));
  c.push(p('GreenHarvest delivers a comprehensive set of features spanning public-facing content, user account management, and administrative tools:'));
  c.push(p(b('Public-Facing Features:'), ' Full landing page with 10 dynamic sections including hero with animated text reveal, featured crops carousel, services grid with 3D hover effects, animated statistics with count-up animations, sustainability showcase, testimonials slider, product showcase with category filtering, success stories, blog preview section, and newsletter signup. Additional features include product catalog, blog system with search, image gallery with lightbox, contact form with map integration, accordion FAQ with categories, dark/light theme toggle, custom cursor with spring physics, Lenis-powered smooth scrolling, Framer Motion page transitions, and animated loading splash screen.'));
  c.push(p(b('User Account Features:'), ' Registration with password confirmation and validation, JWT-based login and logout with session persistence, profile viewing and management, and role-based access control distinguishing regular users from administrators.'));
  c.push(p(b('Administrative Features:'), ' Complete content management for all platform resources including crops, products, blogs, services, FAQs and testimonials. User management with role toggling between user and admin. Contact inquiry management with read and unread tracking. Page view analytics dashboard with 30-day aggregation and per-page breakdown. File upload capabilities for images with type validation and size limits.'));
  c.push(p(b('Security Features:'), ' JWT authentication with HTTP-only cookies and localStorage token storage, bcrypt password hashing with 12 salt rounds, rate limiting at 100 requests per 15 minutes per IP, NoSQL injection prevention via input sanitization, Helmet security headers for XSS and clickjacking protection, CORS configuration restricting cross-origin access, input validation on all critical endpoints, and file upload restrictions limiting types and sizes.'));
  c.push(h2('1.5 Technology Stack Summary'));
  c.push(p('The platform is built on the MERN stack MongoDB, Express, React, Node.js with additional modern tooling. The backend uses Node.js with Express for the web server, Mongoose for MongoDB object modeling, and MongoDB Atlas for cloud database hosting. The frontend uses React 18 with Vite 5 for the build tool, Tailwind CSS 3 for styling, and Framer Motion for animations. The complete technology stack is detailed in Chapter 3 of this documentation.'));
  c.push(p('The development environment uses concurrently to run both backend and frontend servers simultaneously, nodemon for automatic backend restarts, and Vite\'s Hot Module Replacement for instant frontend updates. The project is organized as a monorepo with a root package.json orchestrating both applications.'));
  c.push(h2('1.6 Document Organization'));
  c.push(p('This technical documentation is organized into 20 chapters. Chapters 1 through 4 provide an introduction, project overview, architecture discussion, and setup instructions. Chapters 5 through 8 dive deep into the backend implementation covering the server entry point, database models and schemas, API routes and controllers, and middleware and utility layers. Chapters 9 through 14 cover the frontend implementation including project structure, state management, routing and page components, common components and hooks, admin panel, and animations and theming. Chapters 15 through 17 provide reference material with the complete API specification, authentication flow, and security architecture. Chapters 18 through 20 cover deployment, production readiness, and the future development r
